name: Proof HTML

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  proof-html:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Run HTML Proof
      - name: Proof HTML
        uses: anishathalye/proof-html@v2.2.3
        with:
          directory: .
          check_html: true
          check_opengraph: true
          check_favicon: true
          enforce_https: false
